config/routes.rb
Rails.application.routes.draw do
  resources :loan_terms

  resources :fin_cals

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :managers

  root 'sessions#new'

  resources :quotes

  resources :statuses

  resources :staffs

  resources :inventories

  resources :inventories do
    collection do
      get 'search'
   end
  end

  resources :customers do
    collection do
      get 'search'
    end
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :quotes

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    end
  end
end

app/models/fin_cal.rb
class FinCal < ActiveRecord::Base

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_many :quotes
  has_one :status

    def self.search(search)
      if search
        where('color LIKE ? OR make LIKE? OR model LIKE? OR vin LIKE?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
      end
    end


  end

app/models/loan_term.rb
class LoanTerm < ActiveRecord::Base
end

app/models/manager.rb
class Manager < ActiveRecord::Base
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :status
  belongs_to :customer
  belongs_to :staff
  belongs_to :inventory




end

app/models/staff.rb
class Staff < ActiveRecord::Base
  has_many :quotes
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :quotes
  has_many :inventories

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true, uniqueness: true


  after_destroy :ensure_an_admin_remains
  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end



end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index

  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :department)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/fin_cals_helper.rb
module FinCalsHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/loan_terms_helper.rb
module LoanTermsHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Staffs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.name %></td>
        <td><%= staff.department %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form' %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @staff.department %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>