config/routes.rb
Rails.application.routes.draw do
  resources :loan_terms

  resources :fin_cals

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :managers

  root 'sessions#new'

  resources :quotes

  resources :statuses

  resources :staffs

  resources :inventories

  resources :inventories do
    collection do
      get 'search'
   end
  end

  resources :customers do
    collection do
      get 'search'
    end
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :quotes

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    end
  end
end

app/models/fin_cal.rb
class FinCal < ActiveRecord::Base

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_many :quotes
  has_one :status

    def self.search(search)
      if search
        where('color LIKE ? OR make LIKE? OR model LIKE? OR vin LIKE?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
      end
    end


  end

app/models/loan_term.rb
class LoanTerm < ActiveRecord::Base
end

app/models/manager.rb
class Manager < ActiveRecord::Base
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :status
  belongs_to :customer
  belongs_to :staff
  belongs_to :inventory




end

app/models/staff.rb
class Staff < ActiveRecord::Base
  has_many :quotes
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :quotes
  has_many :inventories

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true, uniqueness: true


  after_destroy :ensure_an_admin_remains
  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end



end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index

  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
    @inventories = Inventory.search(params[:search]) if params[:search].present?
  end


  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:status_id, :vin, :year, :make, :model, :color, :price)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/fin_cals_helper.rb
module FinCalsHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/loan_terms_helper.rb
module LoanTermsHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inventories/_form.html.erb
<%= form_for(@inventory) do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% @inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status_id %><br>
    <%= f.number_field :status_id %>
  </div>
  <div class="field">
    <%= f.label :vin %><br>
    <%= f.text_field :vin %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventory</h1>

<%= form_tag inventories_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>

<ul>
  <% @inventories.each do |inventory| %>
      <li>
        <%= link_to inventory.vin, inventory_path(inventory) %>
        | <%= inventory.year %>
        | <%= inventory.make %>
        | <%= inventory.model %>
        | <%= inventory.color %>
        | <%= inventory.price %>
        | <%= link_to "Edit", edit_inventory_path(inventory) %>
        | <%= link_to "Destroy", inventory_path(inventory), :method => :delete %>
      </li>
  <% end %>
</ul>

<%= link_to 'New Inventory', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form' %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @inventory.status_id %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @inventory.vin %>
</p>

<p>
  <strong>Year:</strong>
  <%= @inventory.year %>
</p>

<p>
  <strong>Make:</strong>
  <%= @inventory.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @inventory.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @inventory.color %>
</p>

<p>
  <strong>Price:</strong>
  <%= @inventory.price %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>