config/routes.rb
Rails.application.routes.draw do
  resources :loan_terms

  resources :fin_cals

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :managers

  root 'sessions#new'

  resources :quotes

  resources :statuses

  resources :staffs

  resources :inventories

  resources :inventories do
    collection do
      get 'search'
   end
  end

  resources :customers do
    collection do
      get 'search'
    end
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :quotes

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    end
  end
end

app/models/fin_cal.rb
class FinCal < ActiveRecord::Base

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_many :quotes
  has_one :status

    def self.search(search)
      if search
        where('color LIKE ? OR make LIKE? OR model LIKE? OR vin LIKE?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
      end
    end


  end

app/models/loan_term.rb
class LoanTerm < ActiveRecord::Base
end

app/models/manager.rb
class Manager < ActiveRecord::Base
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :status
  belongs_to :customer
  belongs_to :staff
  belongs_to :inventory




end

app/models/staff.rb
class Staff < ActiveRecord::Base
  has_many :quotes
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :quotes
  has_many :inventories

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true, uniqueness: true


  after_destroy :ensure_an_admin_remains
  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end



end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index

  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]



  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
    @customers = Customer.search(params[:search]) if params[:search].present?
    #@customers = Customer.where(id: params[:id]) if params[:id].present?

  end

  def search
    #@customers = Customer.search(params[:search])
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :phone, :email)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/fin_cals_helper.rb
module FinCalsHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/loan_terms_helper.rb
module LoanTermsHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<%= form_tag customers_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>

<ul>
  <% @customers.each do |customer| %>
    <li>
      <%= link_to customer.name, customer_path(customer) %>
      | <%= link_to "Edit", edit_customer_path(customer) %>
      | <%= link_to "Destroy", customer_path(customer), :method => :delete %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>