config/routes.rb
Rails.application.routes.draw do
  resources :loan_terms

  resources :fin_cals

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :managers

  root 'sessions#new'

  resources :quotes

  resources :statuses

  resources :staffs

  resources :inventories

  resources :inventories do
    collection do
      get 'search'
   end
  end

  resources :customers do
    collection do
      get 'search'
    end
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :quotes

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    end
  end
end

app/models/fin_cal.rb
class FinCal < ActiveRecord::Base

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_many :quotes
  has_one :status

    def self.search(search)
      if search
        where('color LIKE ? OR make LIKE? OR model LIKE? OR vin LIKE?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
      end
    end


  end

app/models/loan_term.rb
class LoanTerm < ActiveRecord::Base
end

app/models/manager.rb
class Manager < ActiveRecord::Base
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :status
  belongs_to :customer
  belongs_to :staff
  belongs_to :inventory




end

app/models/staff.rb
class Staff < ActiveRecord::Base
  has_many :quotes
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :quotes
  has_many :inventories

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true, uniqueness: true


  after_destroy :ensure_an_admin_remains
  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end



end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index

  end
end

app/controllers/fin_cals_controller.rb
class FinCalsController < ApplicationController
  before_action :set_fin_cal, only: [:show, :edit, :update, :destroy]

  # GET /fin_cals
  # GET /fin_cals.json
  def index
    @fin_cals = FinCal.all
  end

  # GET /fin_cals/1
  # GET /fin_cals/1.json
  def show
    #@loan_array = @fin_cal.cal_loan_table
  end

  # GET /fin_cals/new
  def new
    @fin_cal = FinCal.new
  end

  # GET /fin_cals/1/edit
  def edit
  end

  # POST /fin_cals
  # POST /fin_cals.json
  def create
    @fin_cal = FinCal.new(fin_cal_params)

    respond_to do |format|
      if @fin_cal.save
        format.html { redirect_to @fin_cal, notice: 'Fin cal was successfully created.' }
        format.json { render :show, status: :created, location: @fin_cal }
      else
        format.html { render :new }
        format.json { render json: @fin_cal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fin_cals/1
  # PATCH/PUT /fin_cals/1.json
  def update
    respond_to do |format|
      if @fin_cal.update(fin_cal_params)
        format.html { redirect_to @fin_cal, notice: 'Fin cal was successfully updated.' }
        format.json { render :show, status: :ok, location: @fin_cal }
      else
        format.html { render :edit }
        format.json { render json: @fin_cal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fin_cals/1
  # DELETE /fin_cals/1.json
  def destroy
    @fin_cal.destroy
    respond_to do |format|
      format.html { redirect_to fin_cals_url, notice: 'Fin cal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def loan
    principle = params[:principle]
    interest = params[:interest]
    loan_term = params[:loan_term]
    @loan_array = FinCal.cal_loan_table(principle.to_i, interest.to_f, loan_term.to_i)

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fin_cal
      @fin_cal = FinCal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fin_cal_params
      params.require(:fin_cal).permit(:principle, :interest, :loan_term_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/fin_cals_helper.rb
module FinCalsHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/loan_terms_helper.rb
module LoanTermsHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fin_cals/_form.html.erb
<%= form_for(@fin_cal) do |f| %>
  <% if @fin_cal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fin_cal.errors.count, "error") %> prohibited this fin_cal from being saved:</h2>

      <ul>
      <% @fin_cal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :principle %><br>
    <%= f.number_field :principle %>
  </div>
  <div class="field">
    <%= f.label :interest %><br>
    <%= f.text_field :interest %>
  </div>
  <div class="field">
    <%= f.label :loan_term_id %><br>
    <%= f.number_field :loan_term_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fin_cals/edit.html.erb
<h1>Editing Fin Cal</h1>

<%= render 'form' %>

<%= link_to 'Show', @fin_cal %> |
<%= link_to 'Back', fin_cals_path %>

app/views/fin_cals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Financial Calculator</h1>

<table>
  <thead>
    <tr>
      <th>Principle</th>
      <th>Interest</th>
      <th>Loan term</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fin_cals.each do |fin_cal| %>
      <tr>
        <td><%= fin_cal.principle %></td>
        <td><%= fin_cal.interest %></td>
        <td><%= fin_cal.loan_term_id %></td>
        <td><%= link_to 'Show', fin_cal %></td>
        <td><%= link_to 'Edit', edit_fin_cal_path(fin_cal) %></td>
        <td><%= link_to 'Destroy', fin_cal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fin cal', new_fin_cal_path %>

app/views/fin_cals/new.html.erb
<h1>New Fin Cal</h1>

<%= render 'form' %>

<%= link_to 'Back', fin_cals_path %>

app/views/fin_cals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Principle:</strong>
  <%= @fin_cal.principle %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @fin_cal.interest %>
</p>

<p>
  <strong>Loan term:</strong>
  <%= @fin_cal.loan_term_id %>
</p>

<%= link_to 'Edit', edit_fin_cal_path(@fin_cal) %> |
<%= link_to 'Back', fin_cals_path %>